### ISSUE TITLE
Tokens per minute limit exceeded for get_section_summary()

### ISSUE THREAD

**Issue by JeroenSignicat** [D-Star-AI/dsRAG#75]
dsRAG is working great for me so far!
But processing a big markdown file resulted into the following error:
```
Error processing large.md: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o-mini in organization org-code on tokens per min (TPM): Limit 200000, Requested 1861699. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
Full error details: RateLimitError
Traceback (most recent call last):
  File "/home/me/IdeaProjects/dsRAG/rag_utils.py", line 311, in initialize_knowledge_base
    self.kb.add_document(
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/dsrag/knowledge_base.py", line 265, in add_document
    chunks, chunks_to_embed = auto_context(
                              ^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/dsrag/add_document.py", line 48, in auto_context
    section["summary"] = get_section_summary(
                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/dsrag/auto_context.py", line 122, in get_section_summary
    section_summary = auto_context_model.make_llm_call(chat_messages)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/dsrag/llm.py", line 48, in make_llm_call
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 815, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/me/IdeaProjects/dsRAG/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o-mini in organization org-code on tokens per min (TPM): Limit 200000, Requested 1861699. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
```
My intuition tells me that a section should never end up being that big, so this may be a bug

**Comment by zmccormick7** [comment]
You're right, a section definitely shouldn't be that long. 

Is there a chance that document contains all content on a single line? The way semantic sectioning works is by annotating the document with line numbers and prompting the LLM to pick the starting and ending lines that correspond to sections. The case where all content is on one line is one edge case I know we're not handling, but I've never actually seen it be an issue.

Either way, we should add the same truncation logic that we have in the document summarization function to the section summarization function to avoid the error you're seeing.
